CREATE TABLE [InvIn].[MainMenu]
(
   [Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
   [Name] NVARCHAR(250) NOT NULL,
   [OrderBy] INT NOT NULL,
	[URL] NVARCHAR(250) NOT NULL,
   [Text] NVARCHAR(250) NULL,
   [Icon] NVARCHAR(50) NULL,
   [ToolTip] NVARCHAR(250) NULL,
   [Language] VARCHAR(10) NOT NULL DEFAULT 'en-US'
)
